
// This file is auto-generated. DO NOT EDIT!

using System;
public class AppFnMapping
{
    public static Type[] MAPPING = new Type[451]
    {
        typeof(ProtoVO.common.HeartBeat)
        ,typeof(ProtoVO.common.packet)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.SimpleData)
        ,typeof(ProtoVO.common.error)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.Resource)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.SignalPara)
        ,typeof(ProtoVO.assets.AssetInfo)
        ,typeof(ProtoVO.assets.AssetManifest)
        ,typeof(ProtoVO.assets.BundleInfo)
        ,null
        ,typeof(ProtoVO.chat.ChatLogin)
        ,typeof(ProtoVO.common.BuffObj)
        ,typeof(ProtoVO.common.byteObj)
        ,typeof(ProtoVO.common.EventPacket)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.math.Grid)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.Version)
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatBlock)
        ,typeof(ProtoVO.chat.ChatChannelCreate)
        ,typeof(ProtoVO.chat.ChatChannelDismiss)
        ,typeof(ProtoVO.chat.ChatChannelInvite)
        ,typeof(ProtoVO.chat.ChatChannelObj)
        ,typeof(ProtoVO.chat.ChatMyChannels)
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.OtaVer)
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatHistory)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.Event)
        ,typeof(ProtoVO.common.MainTain)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatOfflineStat)
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatInfo)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.payment.PayoutObj)
        ,typeof(ProtoVO.payment.PayReward)
        ,typeof(ProtoVO.payment.PayVerifyRequest)
        ,typeof(ProtoVO.payment.RechargeInfo)
        ,typeof(ProtoVO.payment.RechargeObj)
        ,typeof(ProtoVO.payment.RechargeRequest)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.common.FrontError)
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatExtData)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatTranslate)
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.chat.ChatChannelChat)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.payment.XsollaToken)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.payment.MarkPayment)
        ,typeof(ProtoVO.payment.GetPaymentMark)
        ,typeof(ProtoVO.payment.DeletePaymentMark)
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,null
        ,typeof(ProtoVO.loading.LoadingRecord)

    };
}
