//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/payment/PayoutObj.proto
namespace ProtoVO
{
    namespace payment
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PayoutObj")]
        public partial class PayoutObj : global::ProtoBuf.IExtensible
        {
            public PayoutObj() {}

            private int _payoutId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"payoutId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int payoutId
            {
                get
                {
                    return _payoutId;
                }
                set
                {
                    _payoutId = value;
                }
            }
            private string _productId;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"productId", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string productId
            {
                get
                {
                    return _productId;
                }
                set
                {
                    _productId = value;
                }
            }
            private float _currency = default(float);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"currency", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
            [global::System.ComponentModel.DefaultValue(default(float))]
            public float currency
            {
                get
                {
                    return _currency;
                }
                set
                {
                    _currency = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}