//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/payment/PayVerifyRequest.proto
namespace ProtoVO
{
    namespace payment
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PayVerifyRequest")]
        public partial class PayVerifyRequest : global::ProtoBuf.IExtensible
        {
            public PayVerifyRequest() {}

            private long _userId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private int _rechargeId;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rechargeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int rechargeId
            {
                get
                {
                    return _rechargeId;
                }
                set
                {
                    _rechargeId = value;
                }
            }
            private int _platform = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int platform
            {
                get
                {
                    return _platform;
                }
                set
                {
                    _platform = value;
                }
            }
            private string _receiptData = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"receiptData", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string receiptData
            {
                get
                {
                    return _receiptData;
                }
                set
                {
                    _receiptData = value;
                }
            }
            private bool _ret = default(bool);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(default(bool))]
            public bool ret
            {
                get
                {
                    return _ret;
                }
                set
                {
                    _ret = value;
                }
            }
            private int _errcode = default(int);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int errcode
            {
                get
                {
                    return _errcode;
                }
                set
                {
                    _errcode = value;
                }
            }
            private string _currencyCode = "";
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"currencyCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string currencyCode
            {
                get
                {
                    return _currencyCode;
                }
                set
                {
                    _currencyCode = value;
                }
            }
            private string _idfa = "";
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"idfa", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string idfa
            {
                get
                {
                    return _idfa;
                }
                set
                {
                    _idfa = value;
                }
            }
            private byte[] _receiptByteData = null;
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"receiptByteData", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public byte[] receiptByteData
            {
                get
                {
                    return _receiptByteData;
                }
                set
                {
                    _receiptByteData = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}