//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/payment/RechargeInfo.proto
// Note: requires additional types generated from: proto/payment/RechargeObj.proto
namespace ProtoVO
{
    namespace payment
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RechargeInfo")]
        public partial class RechargeInfo : global::ProtoBuf.IExtensible
        {
            public RechargeInfo() {}

            private readonly global::System.Collections.Generic.List<payment.RechargeObj> _recharges = new global::System.Collections.Generic.List<payment.RechargeObj>();
            [global::ProtoBuf.ProtoMember(2, Name=@"recharges", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<payment.RechargeObj> recharges
            {
                get
                {
                    return _recharges;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}