//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/payment/RechargeRequest.proto
namespace ProtoVO
{
    namespace payment
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RechargeRequest")]
        public partial class RechargeRequest : global::ProtoBuf.IExtensible
        {
            public RechargeRequest() {}

            private long _userId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private int _countryCode = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"countryCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int countryCode
            {
                get
                {
                    return _countryCode;
                }
                set
                {
                    _countryCode = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}