//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatTranslate.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatTranslate")]
        public partial class ChatTranslate : global::ProtoBuf.IExtensible
        {
            public ChatTranslate() {}

            private string _msgId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string msgId
            {
                get
                {
                    return _msgId;
                }
                set
                {
                    _msgId = value;
                }
            }
            private string _destLang;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"destLang", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string destLang
            {
                get
                {
                    return _destLang;
                }
                set
                {
                    _destLang = value;
                }
            }
            private string _orgMsg = "";
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"orgMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string orgMsg
            {
                get
                {
                    return _orgMsg;
                }
                set
                {
                    _orgMsg = value;
                }
            }
            private string _destMsg = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"destMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string destMsg
            {
                get
                {
                    return _destMsg;
                }
                set
                {
                    _destMsg = value;
                }
            }
            private bool _ret = default(bool);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(default(bool))]
            public bool ret
            {
                get
                {
                    return _ret;
                }
                set
                {
                    _ret = value;
                }
            }
            private string _orgLang = "";
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"orgLang", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string orgLang
            {
                get
                {
                    return _orgLang;
                }
                set
                {
                    _orgLang = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}