//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatChannelObj.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatChannelObj")]
        public partial class ChatChannelObj : global::ProtoBuf.IExtensible
        {
            public ChatChannelObj() {}

            private string _channelId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string channelId
            {
                get
                {
                    return _channelId;
                }
                set
                {
                    _channelId = value;
                }
            }
            private string _name = "";
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string name
            {
                get
                {
                    return _name;
                }
                set
                {
                    _name = value;
                }
            }
            private int _ownerId = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ownerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int ownerId
            {
                get
                {
                    return _ownerId;
                }
                set
                {
                    _ownerId = value;
                }
            }
            private readonly global::System.Collections.Generic.List<int> _memberIds = new global::System.Collections.Generic.List<int>();
            [global::ProtoBuf.ProtoMember(4, Name=@"memberIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public global::System.Collections.Generic.List<int> memberIds
            {
                get
                {
                    return _memberIds;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}