//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatHistory.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatHistory")]
        public partial class ChatHistory : global::ProtoBuf.IExtensible
        {
            public ChatHistory() {}

            private int _type;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int type
            {
                get
                {
                    return _type;
                }
                set
                {
                    _type = value;
                }
            }
            private int _realmId = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"realmId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int realmId
            {
                get
                {
                    return _realmId;
                }
                set
                {
                    _realmId = value;
                }
            }
            private int _realmLevel = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"realmLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int realmLevel
            {
                get
                {
                    return _realmLevel;
                }
                set
                {
                    _realmLevel = value;
                }
            }
            private long _allianceId = default(long);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long allianceId
            {
                get
                {
                    return _allianceId;
                }
                set
                {
                    _allianceId = value;
                }
            }
            private string _privaters = "";
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"privaters", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string privaters
            {
                get
                {
                    return _privaters;
                }
                set
                {
                    _privaters = value;
                }
            }
            private int _page = default(int);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int page
            {
                get
                {
                    return _page;
                }
                set
                {
                    _page = value;
                }
            }
            private readonly global::System.Collections.Generic.List<byte[]> _chats = new global::System.Collections.Generic.List<byte[]>();
            [global::ProtoBuf.ProtoMember(7, Name=@"chats", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<byte[]> chats
            {
                get
                {
                    return _chats;
                }
            }

            private string _channelId = "";
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string channelId
            {
                get
                {
                    return _channelId;
                }
                set
                {
                    _channelId = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}