//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatInfo.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"realmInfo")]
        public partial class realmInfo : global::ProtoBuf.IExtensible
        {
            public realmInfo() {}

            private int _realmLevel;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"realmLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int realmLevel
            {
                get
                {
                    return _realmLevel;
                }
                set
                {
                    _realmLevel = value;
                }
            }
            private readonly global::System.Collections.Generic.List<int> _realmIds = new global::System.Collections.Generic.List<int>();
            [global::ProtoBuf.ProtoMember(2, Name=@"realmIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public global::System.Collections.Generic.List<int> realmIds
            {
                get
                {
                    return _realmIds;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatExtData")]
        public partial class ChatExtData : global::ProtoBuf.IExtensible
        {
            public ChatExtData() {}

            private int _type = default(int);
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int type
            {
                get
                {
                    return _type;
                }
                set
                {
                    _type = value;
                }
            }
            private string _data = "";
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string data
            {
                get
                {
                    return _data;
                }
                set
                {
                    _data = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatInfo")]
        public partial class ChatInfo : global::ProtoBuf.IExtensible
        {
            public ChatInfo() {}

            private long _userId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private string _userNick = "";
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string userNick
            {
                get
                {
                    return _userNick;
                }
                set
                {
                    _userNick = value;
                }
            }
            private int _realmId = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"realmId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int realmId
            {
                get
                {
                    return _realmId;
                }
                set
                {
                    _realmId = value;
                }
            }
            private int _realmLevel = default(int);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"realmLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int realmLevel
            {
                get
                {
                    return _realmLevel;
                }
                set
                {
                    _realmLevel = value;
                }
            }
            private long _allianceId = default(long);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long allianceId
            {
                get
                {
                    return _allianceId;
                }
                set
                {
                    _allianceId = value;
                }
            }
            private long _receiverId = default(long);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"receiverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long receiverId
            {
                get
                {
                    return _receiverId;
                }
                set
                {
                    _receiverId = value;
                }
            }
            private string _msg = "";
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string msg
            {
                get
                {
                    return _msg;
                }
                set
                {
                    _msg = value;
                }
            }
            private byte[] _extBinData = null;
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"extBinData", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public byte[] extBinData
            {
                get
                {
                    return _extBinData;
                }
                set
                {
                    _extBinData = value;
                }
            }
            private int _sendTime = default(int);
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int sendTime
            {
                get
                {
                    return _sendTime;
                }
                set
                {
                    _sendTime = value;
                }
            }
            private long _microTime = default(long);
            [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"microTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long microTime
            {
                get
                {
                    return _microTime;
                }
                set
                {
                    _microTime = value;
                }
            }
            private int _portraitId = default(int);
            [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"portraitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int portraitId
            {
                get
                {
                    return _portraitId;
                }
                set
                {
                    _portraitId = value;
                }
            }
            private string _allianceName = "";
            [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"allianceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string allianceName
            {
                get
                {
                    return _allianceName;
                }
                set
                {
                    _allianceName = value;
                }
            }
            private int _vipLevel = default(int);
            [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int vipLevel
            {
                get
                {
                    return _vipLevel;
                }
                set
                {
                    _vipLevel = value;
                }
            }
            private readonly global::System.Collections.Generic.List<chat.ChatExtData> _extDatas = new global::System.Collections.Generic.List<chat.ChatExtData>();
            [global::ProtoBuf.ProtoMember(14, Name=@"extDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<chat.ChatExtData> extDatas
            {
                get
                {
                    return _extDatas;
                }
            }

            private string _secretKey = "";
            [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"secretKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string secretKey
            {
                get
                {
                    return _secretKey;
                }
                set
                {
                    _secretKey = value;
                }
            }
            private int _isGlobal = default(int);
            [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"isGlobal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int isGlobal
            {
                get
                {
                    return _isGlobal;
                }
                set
                {
                    _isGlobal = value;
                }
            }
            private int _isGlobalFree = default(int);
            [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"isGlobalFree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int isGlobalFree
            {
                get
                {
                    return _isGlobalFree;
                }
                set
                {
                    _isGlobalFree = value;
                }
            }
            private string _receiverNick = "";
            [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"receiverNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string receiverNick
            {
                get
                {
                    return _receiverNick;
                }
                set
                {
                    _receiverNick = value;
                }
            }
            private int _receiverPortraitId = default(int);
            [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"receiverPortraitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int receiverPortraitId
            {
                get
                {
                    return _receiverPortraitId;
                }
                set
                {
                    _receiverPortraitId = value;
                }
            }
            private int _isSystem = default(int);
            [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"isSystem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int isSystem
            {
                get
                {
                    return _isSystem;
                }
                set
                {
                    _isSystem = value;
                }
            }
            private readonly global::System.Collections.Generic.List<chat.realmInfo> _realms = new global::System.Collections.Generic.List<chat.realmInfo>();
            [global::ProtoBuf.ProtoMember(21, Name=@"realms", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<chat.realmInfo> realms
            {
                get
                {
                    return _realms;
                }
            }

            private readonly global::System.Collections.Generic.List<string> _extStrDatas = new global::System.Collections.Generic.List<string>();
            [global::ProtoBuf.ProtoMember(22, Name=@"extStrDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<string> extStrDatas
            {
                get
                {
                    return _extStrDatas;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}