//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatChannelChat.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatChannelChat")]
        public partial class ChatChannelChat : global::ProtoBuf.IExtensible
        {
            public ChatChannelChat() {}

            private string _channelId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string channelId
            {
                get
                {
                    return _channelId;
                }
                set
                {
                    _channelId = value;
                }
            }
            private long _userId;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private string _userNick = "";
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userNick", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string userNick
            {
                get
                {
                    return _userNick;
                }
                set
                {
                    _userNick = value;
                }
            }
            private string _msg = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string msg
            {
                get
                {
                    return _msg;
                }
                set
                {
                    _msg = value;
                }
            }
            private int _sendTime = default(int);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int sendTime
            {
                get
                {
                    return _sendTime;
                }
                set
                {
                    _sendTime = value;
                }
            }
            private long _microTime = default(long);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"microTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long microTime
            {
                get
                {
                    return _microTime;
                }
                set
                {
                    _microTime = value;
                }
            }
            private int _portraitId = default(int);
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"portraitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int portraitId
            {
                get
                {
                    return _portraitId;
                }
                set
                {
                    _portraitId = value;
                }
            }
            private readonly global::System.Collections.Generic.List<chat.ChatChannelChat.ChatExtData> _extDatas = new global::System.Collections.Generic.List<chat.ChatChannelChat.ChatExtData>();
            [global::ProtoBuf.ProtoMember(8, Name=@"extDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<chat.ChatChannelChat.ChatExtData> extDatas
            {
                get
                {
                    return _extDatas;
                }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatExtData")]
            public partial class ChatExtData : global::ProtoBuf.IExtensible
            {
                public ChatExtData() {}

                private int _type = default(int);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int type
                {
                    get
                    {
                        return _type;
                    }
                    set
                    {
                        _type = value;
                    }
                }
                private string _data = "";
                [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
                [global::System.ComponentModel.DefaultValue("")]
                public string data
                {
                    get
                    {
                        return _data;
                    }
                    set
                    {
                        _data = value;
                    }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                {
                    return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}