//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatLogin.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatLogin")]
        public partial class ChatLogin : global::ProtoBuf.IExtensible
        {
            public ChatLogin() {}

            private long _userId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private string _nick = "";
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string nick
            {
                get
                {
                    return _nick;
                }
                set
                {
                    _nick = value;
                }
            }
            private int _realmId = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"realmId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int realmId
            {
                get
                {
                    return _realmId;
                }
                set
                {
                    _realmId = value;
                }
            }
            private int _realmLevel = default(int);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"realmLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int realmLevel
            {
                get
                {
                    return _realmLevel;
                }
                set
                {
                    _realmLevel = value;
                }
            }
            private long _allianceId = default(long);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long allianceId
            {
                get
                {
                    return _allianceId;
                }
                set
                {
                    _allianceId = value;
                }
            }
            private string _language = "";
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string language
            {
                get
                {
                    return _language;
                }
                set
                {
                    _language = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}