//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/chat/ChatBlock.proto
namespace ProtoVO
{
    namespace chat
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatBlock")]
        public partial class ChatBlock : global::ProtoBuf.IExtensible
        {
            public ChatBlock() {}

            private long _userId;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private long _blockedUserId;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"blockedUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public long blockedUserId
            {
                get
                {
                    return _blockedUserId;
                }
                set
                {
                    _blockedUserId = value;
                }
            }
            private long _allianceId = default(long);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"allianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long allianceId
            {
                get
                {
                    return _allianceId;
                }
                set
                {
                    _allianceId = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}