//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/BuffObj.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuffObj")]
        public partial class BuffObj : global::ProtoBuf.IExtensible
        {
            public BuffObj() {}

            private int _id;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int id
            {
                get
                {
                    return _id;
                }
                set
                {
                    _id = value;
                }
            }
            private int _detailGroup = default(int);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"detailGroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int detailGroup
            {
                get
                {
                    return _detailGroup;
                }
                set
                {
                    _detailGroup = value;
                }
            }
            private long _detailId = default(long);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"detailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long detailId
            {
                get
                {
                    return _detailId;
                }
                set
                {
                    _detailId = value;
                }
            }
            private int _expire = default(int);
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"expire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int expire
            {
                get
                {
                    return _expire;
                }
                set
                {
                    _expire = value;
                }
            }
            private float _ratio = default(float);
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ratio", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
            [global::System.ComponentModel.DefaultValue(default(float))]
            public float ratio
            {
                get
                {
                    return _ratio;
                }
                set
                {
                    _ratio = value;
                }
            }
            private int _tag = default(int);
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int tag
            {
                get
                {
                    return _tag;
                }
                set
                {
                    _tag = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}