//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/error.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"error")]
        public partial class error : global::ProtoBuf.IExtensible
        {
            public error() {}

            private int _funcode;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"funcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int funcode
            {
                get
                {
                    return _funcode;
                }
                set
                {
                    _funcode = value;
                }
            }
            private int _errcode = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int errcode
            {
                get
                {
                    return _errcode;
                }
                set
                {
                    _errcode = value;
                }
            }
            private int _popup = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"popup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int popup
            {
                get
                {
                    return _popup;
                }
                set
                {
                    _popup = value;
                }
            }
            private int _restart = default(int);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"restart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int restart
            {
                get
                {
                    return _restart;
                }
                set
                {
                    _restart = value;
                }
            }
            private string _info = "";
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string info
            {
                get
                {
                    return _info;
                }
                set
                {
                    _info = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}