//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/FrontError.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrontError")]
        public partial class FrontError : global::ProtoBuf.IExtensible
        {
            public FrontError() {}

            private long _dt = default(long);
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long dt
            {
                get
                {
                    return _dt;
                }
                set
                {
                    _dt = value;
                }
            }
            private long _userId = default(long);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private string _mobile = "";
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mobile", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string mobile
            {
                get
                {
                    return _mobile;
                }
                set
                {
                    _mobile = value;
                }
            }
            private string _os = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string os
            {
                get
                {
                    return _os;
                }
                set
                {
                    _os = value;
                }
            }
            private string _osVer = "";
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"osVer", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string osVer
            {
                get
                {
                    return _osVer;
                }
                set
                {
                    _osVer = value;
                }
            }
            private string _gameVer = "";
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gameVer", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string gameVer
            {
                get
                {
                    return _gameVer;
                }
                set
                {
                    _gameVer = value;
                }
            }
            private string _packet = "";
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"packet", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string packet
            {
                get
                {
                    return _packet;
                }
                set
                {
                    _packet = value;
                }
            }
            private string _msg = "";
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string msg
            {
                get
                {
                    return _msg;
                }
                set
                {
                    _msg = value;
                }
            }
            private byte[] _stack = null;
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"stack", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public byte[] stack
            {
                get
                {
                    return _stack;
                }
                set
                {
                    _stack = value;
                }
            }
            private string _errorType = "";
            [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"errorType", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string errorType
            {
                get
                {
                    return _errorType;
                }
                set
                {
                    _errorType = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}