//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/MainTain.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainTain")]
        public partial class MainTain : global::ProtoBuf.IExtensible
        {
            public MainTain() {}

            private string _serviceType;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serviceType", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string serviceType
            {
                get
                {
                    return _serviceType;
                }
                set
                {
                    _serviceType = value;
                }
            }
            private int _status;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int status
            {
                get
                {
                    return _status;
                }
                set
                {
                    _status = value;
                }
            }
            private int _endTime;
            [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int endTime
            {
                get
                {
                    return _endTime;
                }
                set
                {
                    _endTime = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}