//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/OtaVer.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtaVer")]
        public partial class OtaVer : global::ProtoBuf.IExtensible
        {
            public OtaVer() {}

            private uint _otaVer;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"otaVer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public uint otaVer
            {
                get
                {
                    return _otaVer;
                }
                set
                {
                    _otaVer = value;
                }
            }
            private uint _ver;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public uint ver
            {
                get
                {
                    return _ver;
                }
                set
                {
                    _ver = value;
                }
            }
            private string _md5 = "";
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"md5", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string md5
            {
                get
                {
                    return _md5;
                }
                set
                {
                    _md5 = value;
                }
            }
            private string _host = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string host
            {
                get
                {
                    return _host;
                }
                set
                {
                    _host = value;
                }
            }
            private string _path = "";
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string path
            {
                get
                {
                    return _path;
                }
                set
                {
                    _path = value;
                }
            }
            private string _suffix = "";
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"suffix", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string suffix
            {
                get
                {
                    return _suffix;
                }
                set
                {
                    _suffix = value;
                }
            }
            private uint _clientVer = default(uint);
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"clientVer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint clientVer
            {
                get
                {
                    return _clientVer;
                }
                set
                {
                    _clientVer = value;
                }
            }
            private uint _clientUpgrade = default(uint);
            [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"clientUpgrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint clientUpgrade
            {
                get
                {
                    return _clientUpgrade;
                }
                set
                {
                    _clientUpgrade = value;
                }
            }
            private string _appDownloadUrl = "";
            [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"appDownloadUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string appDownloadUrl
            {
                get
                {
                    return _appDownloadUrl;
                }
                set
                {
                    _appDownloadUrl = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}