//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/packet.proto
// Note: requires additional types generated from: proto/common/byteObj.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"packet")]
        public partial class packet : global::ProtoBuf.IExtensible
        {
            public packet() {}

            private int _funcode;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"funcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int funcode
            {
                get
                {
                    return _funcode;
                }
                set
                {
                    _funcode = value;
                }
            }
            private int _opcode = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"opcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int opcode
            {
                get
                {
                    return _opcode;
                }
                set
                {
                    _opcode = value;
                }
            }
            private byte[] _data = null;
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public byte[] data
            {
                get
                {
                    return _data;
                }
                set
                {
                    _data = value;
                }
            }
            private string _hamalNode = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hamalNode", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string hamalNode
            {
                get
                {
                    return _hamalNode;
                }
                set
                {
                    _hamalNode = value;
                }
            }
            private byte[] _clientPid = null;
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clientPid", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue(null)]
            public byte[] clientPid
            {
                get
                {
                    return _clientPid;
                }
                set
                {
                    _clientPid = value;
                }
            }
            private long _playerId = default(long);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long playerId
            {
                get
                {
                    return _playerId;
                }
                set
                {
                    _playerId = value;
                }
            }
            private long _timestamp = default(long);
            [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long timestamp
            {
                get
                {
                    return _timestamp;
                }
                set
                {
                    _timestamp = value;
                }
            }
            private readonly global::System.Collections.Generic.List<common.byteObj> _batchPackets = new global::System.Collections.Generic.List<common.byteObj>();
            [global::ProtoBuf.ProtoMember(8, Name=@"batchPackets", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<common.byteObj> batchPackets
            {
                get
                {
                    return _batchPackets;
                }
            }

            private readonly global::System.Collections.Generic.List<int> _castDataIds = new global::System.Collections.Generic.List<int>();
            [global::ProtoBuf.ProtoMember(9, Name=@"castDataIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public global::System.Collections.Generic.List<int> castDataIds
            {
                get
                {
                    return _castDataIds;
                }
            }

            private readonly global::System.Collections.Generic.List<float> _castReceiverIds = new global::System.Collections.Generic.List<float>();
            [global::ProtoBuf.ProtoMember(10, Name=@"castReceiverIds", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
            public global::System.Collections.Generic.List<float> castReceiverIds
            {
                get
                {
                    return _castReceiverIds;
                }
            }

            private string _clientIp = "";
            [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"clientIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string clientIp
            {
                get
                {
                    return _clientIp;
                }
                set
                {
                    _clientIp = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}