//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/Resource.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Resource")]
        public partial class Resource : global::ProtoBuf.IExtensible
        {
            public Resource() {}

            private int _food = default(int);
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"food", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int food
            {
                get
                {
                    return _food;
                }
                set
                {
                    _food = value;
                }
            }
            private int _wood = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int wood
            {
                get
                {
                    return _wood;
                }
                set
                {
                    _wood = value;
                }
            }
            private int _stone = default(int);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int stone
            {
                get
                {
                    return _stone;
                }
                set
                {
                    _stone = value;
                }
            }
            private int _ore = default(int);
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int ore
            {
                get
                {
                    return _ore;
                }
                set
                {
                    _ore = value;
                }
            }
            private int _gold = default(int);
            [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int gold
            {
                get
                {
                    return _gold;
                }
                set
                {
                    _gold = value;
                }
            }
            private int _diamond = default(int);
            [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int diamond
            {
                get
                {
                    return _diamond;
                }
                set
                {
                    _diamond = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}