//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common/Version.proto
namespace ProtoVO
{
    namespace common
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Version")]
        public partial class Version : global::ProtoBuf.IExtensible
        {
            public Version() {}

            private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
            [global::ProtoBuf.ProtoMember(1, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<string> name
            {
                get
                {
                    return _name;
                }
            }

            private readonly global::System.Collections.Generic.List<uint> _version = new global::System.Collections.Generic.List<uint>();
            [global::ProtoBuf.ProtoMember(2, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public global::System.Collections.Generic.List<uint> version
            {
                get
                {
                    return _version;
                }
            }

            private uint _platform = default(uint);
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(uint))]
            public uint platform
            {
                get
                {
                    return _platform;
                }
                set
                {
                    _platform = value;
                }
            }
            private string _language = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string language
            {
                get
                {
                    return _language;
                }
                set
                {
                    _language = value;
                }
            }
            private readonly global::System.Collections.Generic.List<string> _md5 = new global::System.Collections.Generic.List<string>();
            [global::ProtoBuf.ProtoMember(5, Name=@"md5", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<string> md5
            {
                get
                {
                    return _md5;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}