//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/admin/ManagePara.proto
// Note: requires additional types generated from: proto/common/SignalPara.proto
namespace ProtoVO
{
    namespace admin
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ManagePara")]
        public partial class ManagePara : global::ProtoBuf.IExtensible
        {
            public ManagePara() {}

            private readonly global::System.Collections.Generic.List<common.SignalPara> _paras = new global::System.Collections.Generic.List<common.SignalPara>();
            [global::ProtoBuf.ProtoMember(1, Name=@"paras", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<common.SignalPara> paras
            {
                get
                {
                    return _paras;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}