//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/admin/ManageResult.proto
namespace ProtoVO
{
    namespace admin
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ManageResult")]
        public partial class ManageResult : global::ProtoBuf.IExtensible
        {
            public ManageResult() {}

            private int _ret;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            public int ret
            {
                get
                {
                    return _ret;
                }
                set
                {
                    _ret = value;
                }
            }
            private int _errcode = default(int);
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(int))]
            public int errcode
            {
                get
                {
                    return _errcode;
                }
                set
                {
                    _errcode = value;
                }
            }
            private string _errmsg = "";
            [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string errmsg
            {
                get
                {
                    return _errmsg;
                }
                set
                {
                    _errmsg = value;
                }
            }
            private string _jsonrecs = "";
            [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jsonrecs", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string jsonrecs
            {
                get
                {
                    return _jsonrecs;
                }
                set
                {
                    _jsonrecs = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}