//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/assets/AssetManifest.proto
// Note: requires additional types generated from: proto/assets/AssetInfo.proto
// Note: requires additional types generated from: proto/assets/BundleInfo.proto
namespace ProtoVO
{
    namespace assets
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssetManifest")]
        public partial class AssetManifest : global::ProtoBuf.IExtensible
        {
            public AssetManifest() {}

            private string _version = "";
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string version
            {
                get
                {
                    return _version;
                }
                set
                {
                    _version = value;
                }
            }
            private readonly global::System.Collections.Generic.List<assets.BundleInfo> _bundleList = new global::System.Collections.Generic.List<assets.BundleInfo>();
            [global::ProtoBuf.ProtoMember(2, Name=@"bundleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<assets.BundleInfo> bundleList
            {
                get
                {
                    return _bundleList;
                }
            }

            private readonly global::System.Collections.Generic.List<assets.AssetInfo> _assetList = new global::System.Collections.Generic.List<assets.AssetInfo>();
            [global::ProtoBuf.ProtoMember(3, Name=@"assetList", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<assets.AssetInfo> assetList
            {
                get
                {
                    return _assetList;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}