//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/assets/AssetInfo.proto
namespace ProtoVO
{
    namespace assets
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssetInfo")]
        public partial class AssetInfo : global::ProtoBuf.IExtensible
        {
            public AssetInfo() {}

            private string _name = "";
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string name
            {
                get
                {
                    return _name;
                }
                set
                {
                    _name = value;
                }
            }
            private string _bundle = "";
            [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bundle", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string bundle
            {
                get
                {
                    return _bundle;
                }
                set
                {
                    _bundle = value;
                }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}