//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/assets/BundleInfo.proto
namespace ProtoVO
{
    namespace assets
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BundleInfo")]
        public partial class BundleInfo : global::ProtoBuf.IExtensible
        {
            public BundleInfo() {}

            private string _name = "";
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
            [global::System.ComponentModel.DefaultValue("")]
            public string name
            {
                get
                {
                    return _name;
                }
                set
                {
                    _name = value;
                }
            }
            private readonly global::System.Collections.Generic.List<string> _deps = new global::System.Collections.Generic.List<string>();
            [global::ProtoBuf.ProtoMember(2, Name=@"deps", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<string> deps
            {
                get
                {
                    return _deps;
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}