//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/loading/LoadingRecord.proto
namespace ProtoVO
{
    namespace loading
    {
        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadingRecord")]
        public partial class LoadingRecord : global::ProtoBuf.IExtensible
        {
            public LoadingRecord() {}

            private long _userId = default(long);
            [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
            [global::System.ComponentModel.DefaultValue(default(long))]
            public long userId
            {
                get
                {
                    return _userId;
                }
                set
                {
                    _userId = value;
                }
            }
            private readonly global::System.Collections.Generic.List<loading.LoadingRecord.Record> _record = new global::System.Collections.Generic.List<loading.LoadingRecord.Record>();
            [global::ProtoBuf.ProtoMember(2, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public global::System.Collections.Generic.List<loading.LoadingRecord.Record> record
            {
                get
                {
                    return _record;
                }
            }

            [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Record")]
            public partial class Record : global::ProtoBuf.IExtensible
            {
                public Record() {}

                private int _step = default(int);
                [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int step
                {
                    get
                    {
                        return _step;
                    }
                    set
                    {
                        _step = value;
                    }
                }
                private int _start = default(int);
                [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int start
                {
                    get
                    {
                        return _start;
                    }
                    set
                    {
                        _start = value;
                    }
                }
                private int _end = default(int);
                [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int end
                {
                    get
                    {
                        return _end;
                    }
                    set
                    {
                        _end = value;
                    }
                }
                private int _num = default(int);
                [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
                [global::System.ComponentModel.DefaultValue(default(int))]
                public int num
                {
                    get
                    {
                        return _num;
                    }
                    set
                    {
                        _num = value;
                    }
                }
                private global::ProtoBuf.IExtension extensionObject;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                {
                    return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
                }
            }

            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
            }
        }

    }
}